Attribute VB_Name = "ECNLIB00_VARGRAL"
Option Explicit

Global Const GK_COLOR_LET_NULL As Double = &HC0C0C0

Global GO_ECNLIB00_CONST As New ECNVB6LIB.ECNLIB00_CONST
Global GO_ECNLIB01_FUNSUB As New ECNVB6LIB.ECNLIB01_FUNSUB
Global GO_ECNLIB02_VALIDA As New ECNVB6LIB.ECNLIB02_VALIDA
