Attribute VB_Name = "Module2"
Public G_SQL_USER As String
Public G_SQL_UPWD As String
Public G_BD_MAIN As String
Public G_BD_IMAG As String
Public G_BD_SEG As String
Public G_CONEXION_SQL As String
Public G_CONEXION_XLS As String
Public G_CONEXION_SQL_SEG As String
